name: track_your_stop
description: Track your favorite public transport stops.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # iOS style icons.
  cupertino_icons: ^1.0.6
  # Logging
  logger: ^2.0.2+1
  # Date formatting
  intl: any
  # State management
  hooks_riverpod: ^2.3.8
  # Routing
  auto_route: ^5.0.3
  # Database storage
  sqflite: ^2.2.8+4
  # Toasts
  fluttertoast: ^8.2.3
  # Http requests
  http: ^0.13.6
  # List builder for http requests
  flutter_typeahead: ^4.8.0
  # Settings ui framework
  settings_ui: ^2.0.2
  # UI Image bubbles
  flutter_image_stack: ^0.0.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  # Linter
  flutter_lints: ^2.0.3
  # Page routing
  auto_route_generator: ^5.0.3
  # Generate route files
  build_runner: ^2.3.2
  # App icon helper
  flutter_launcher_icons: ^0.13.1
  # Http requests
  grpc: ^3.1.0
  # Http response parser
  http_parser: ^4.0.0

# Flutter related packages
flutter:
  generate: true
  # Enable material design
  uses-material-design: true
  # Add assets
  assets:
    - assets/images/

# Flutter app icon
flutter_launcher_icons:
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  android: true
  ios: true
  image_path_android: assets/images/logo-android.png
  image_path: assets/images/logo-ios.png
